{{- if .Values.postgresql.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kresus.fullname" . }}
  labels:
    {{- include "kresus.labels" . | nindent 4 }}
data:
  KRESUS_DB_USERNAME: {{ .Values.postgresql.auth.username | b64enc | quote }}
  KRESUS_DB_PASSWORD: {{ .Values.postgresql.auth.password | b64enc | quote }}
{{- end }}
