# See https://framagit.org/kresusapp/kresus/-/blob/main/support/docker/config.example.ini
config:
  existingSecretRef:
    name: '{{ include "kresus.fullname" . }}-config-sample'

test:
  sampleConfig:
    secret:
      create: true
