{{- if .Values.test.sampleConfig.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kresus.fullname" . }}-config-sample
stringData:
  config.ini: |
    [kresus]
    force_demo_mode=true

{{- end }}
