{{- if .Values.test.sampleConfig.configMap.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kresus.fullname" . }}-config-sample
data:
  config.ini: |
    [kresus]
    force_demo_mode=true
{{- end }}
