apiVersion: v2
name: kresus
description: |
  Open-source libre self-hosted personal finance manager.
  https://github.com/kresusapp/kresus

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "latest"

maintainers:
- name: rm3l
  email: armel@rm3l.org
  url: https://rm3l.org

dependencies:
- name: postgresql
  # See https://github.com/bitnami/charts/tree/master/bitnami/postgresql
  version: "16.7.15"
  repository: "https://charts.bitnami.com/bitnami"
  condition: postgresql.enabled
- name: apprise-api
  alias: apprise
  # See https://github.com/tieum/helm-charts/tree/main/charts/apprise-api
  version: "0.0.5"
  repository: "https://tieum.github.io/helm-charts"
  condition: apprise.enabled
