apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "atuin.fullname" . }}
  labels:
    {{- include "atuin.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "atuin.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "atuin.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "atuin.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.postgresql.enabled }}
      initContainers:
        - name: wait-db-service
          image: busybox:1.28
          securityContext:
            readOnlyRootFilesystem: true
            runAsUser: 65534
            runAsGroup: 65534
          command: ['sh', '-c', "until nslookup {{ include "atuin.fullname" . }}-postgresql.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for {{ include "atuin.fullname" . }}-postgresql.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; sleep 2; done"]
          resources:
            limits:
              cpu: 100m
              memory: 10Mi
            requests:
              cpu: 100m
              memory: 1Mi
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          args:
            - server
            - start
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ATUIN_DB_URI
            {{- if .Values.sqlite.enabled }}
              value: "sqlite:///data/atuin.db"
            {{- else }}
              valueFrom:
                secretKeyRef:
                  name: {{ ternary (include "atuin.fullname" .) .Values.postgresql.auth.existingSecret .Values.postgresql.enabled }}
                  key: {{ ternary "ATUIN_DB_URI" .Values.postgresql.auth.existingSecretKey .Values.postgresql.enabled }}
                  optional: false
            {{- end }}
            - name: ATUIN_HOST
              value: 0.0.0.0
            - name: ATUIN_PORT
              value: "{{ .Values.service.port }}"
            - name: ATUIN_OPEN_REGISTRATION
              value: "{{ .Values.atuin.openRegistration }}"
            {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: app-port
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: app-port
          readinessProbe:
            httpGet:
              path: /
              port: app-port
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /config
              name: {{ include "atuin.fullname" . }}-config
            {{- if .Values.sqlite.enabled }}
            - mountPath: /data
              name: {{ include "atuin.fullname" . }}-data-sqlite
            {{- end }}
      volumes:
        - name: {{ include "atuin.fullname" . }}-config
          persistentVolumeClaim:
            claimName: {{ include "atuin.fullname" . }}-config
        {{- if .Values.sqlite.enabled }}
        - name: {{ include "atuin.fullname" . }}-data-sqlite
          persistentVolumeClaim:
            claimName: {{ include "atuin.fullname" . }}-data-sqlite
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

